---
categories:
  - Assembly
description: >
  Compute genomic consensus and call variants using PacBio reads mapped to a
  reference
homepage_url: https://github.com/PacificBiosciences/gcpp
long_description: >
  Compute genomic consensus and call variants using PacBio reads mapped to a
  reference
name: pbgcpp
owner: galaxy-australia
remote_repository_url: https://github.com/usegalaxy-au/galaxy-local-tools/tree/master/tools/pbgcpp
type: unrestricted
