---
categories:
  - Assembly
description: A minimap2 SMRT wrapper for PacBio data.
homepage_url: https://github.com/PacificBiosciences/pbmm2
long_description: >
  A minimap2 SMRT wrapper for PacBio data. Native PacBio data in to native
  PacBio BAM out.
name: pbmm2
owner: galaxy-australia
remote_repository_url: https://github.com/usegalaxy-au/galaxy-local-tools/tree/master/tools/pbmm2
type: unrestricted
